
default_events:
- check_suite
- pull_request
- pull_request_review
- status

default_permissions:
  
  administration: read
  checks: read
  contents: write
  pull_requests: write
  statuses: read

name:  Auto-Merge App


description: Automerging Pull Requests once Status Checks pass and when atleast one review is done
Default: true
public: false
